export const FUN_SCHEMA_VERSION = '4';

export const FUN_COMMANDS = Object.freeze({
  XP: 'xp',
  PERFIL: 'perfil',
  RANK: 'rank',
  RANK_COINS: 'rankcoins',
  DAILY: 'daily',
  HELP: 'help',
  PAY: 'pay',
  COINS: 'coins',
  MARRY: 'marry',
  DIVORCE: 'divorce',
  SHIP: 'ship',
  ACCEPT: 'accept',
  DECLINE: 'decline',
  FLIP: 'flip',
  JOB: 'job',
  LUCKY: 'lucky',
  BET: 'bet',
  SHOP: 'shop',
  BUY: 'buy',
  TITLE: 'title',
});

export const FUN_COMMAND_ALIASES = Object.freeze({
  xp: FUN_COMMANDS.XP,
  perfil: FUN_COMMANDS.PERFIL,
  profile: FUN_COMMANDS.PERFIL,
  rank: FUN_COMMANDS.RANK,
  top: FUN_COMMANDS.RANK,
  leaderboard: FUN_COMMANDS.RANK,
  rankcoins: FUN_COMMANDS.RANK_COINS,
  topcoins: FUN_COMMANDS.RANK_COINS,
  coinrank: FUN_COMMANDS.RANK_COINS,
  moedasrank: FUN_COMMANDS.RANK_COINS,
  rankmoedas: FUN_COMMANDS.RANK_COINS,
  daily: FUN_COMMANDS.DAILY,
  diario: FUN_COMMANDS.DAILY,
  help: FUN_COMMANDS.HELP,
  ajuda: FUN_COMMANDS.HELP,
  pay: FUN_COMMANDS.PAY,
  pagar: FUN_COMMANDS.PAY,
  coins: FUN_COMMANDS.COINS,
  moedas: FUN_COMMANDS.COINS,
  saldo: FUN_COMMANDS.COINS,
  marry: FUN_COMMANDS.MARRY,
  casar: FUN_COMMANDS.MARRY,
  divorce: FUN_COMMANDS.DIVORCE,
  divorciar: FUN_COMMANDS.DIVORCE,
  ship: FUN_COMMANDS.SHIP,
  aceitar: FUN_COMMANDS.ACCEPT,
  accept: FUN_COMMANDS.ACCEPT,
  sim: FUN_COMMANDS.ACCEPT,
  yes: FUN_COMMANDS.ACCEPT,
  recusar: FUN_COMMANDS.DECLINE,
  recusa: FUN_COMMANDS.DECLINE,
  decline: FUN_COMMANDS.DECLINE,
  nao: FUN_COMMANDS.DECLINE,
  não: FUN_COMMANDS.DECLINE,
  no: FUN_COMMANDS.DECLINE,
  cf: FUN_COMMANDS.FLIP,
  flip: FUN_COMMANDS.FLIP,
  caracoroa: FUN_COMMANDS.FLIP,
  coinflip: FUN_COMMANDS.FLIP,
  job: FUN_COMMANDS.JOB,
  trabalhar: FUN_COMMANDS.JOB,
  work: FUN_COMMANDS.JOB,
  sorte: FUN_COMMANDS.LUCKY,
  lucky: FUN_COMMANDS.LUCKY,
  roleta: FUN_COMMANDS.LUCKY,
  aposta: FUN_COMMANDS.BET,
  bet: FUN_COMMANDS.BET,
  apostar: FUN_COMMANDS.BET,
  loja: FUN_COMMANDS.SHOP,
  shop: FUN_COMMANDS.SHOP,
  store: FUN_COMMANDS.SHOP,
  comprar: FUN_COMMANDS.BUY,
  buy: FUN_COMMANDS.BUY,
  titulo: FUN_COMMANDS.TITLE,
  title: FUN_COMMANDS.TITLE,
});

export const ACTION_TYPE = Object.freeze({
  MARRY: 'marry',
  BET_COINFLIP: 'bet_coinflip',
});

export const DAY_MS = 24 * 60 * 60 * 1000;
export const PROPOSAL_TTL_MS = 5 * 60 * 1000;
export const BET_TTL_MS = 5 * 60 * 1000;

/** Defaults do bot Fun standalone (não herda config do TMB). */
export const DEFAULT_FUN_CONFIG = Object.freeze({
  enabled: true,
  prefix: '/',
  cooldownMs: 60_000,
  xpMin: 15,
  xpMax: 25,
  dailyXp: 150,
  dailyCoins: 50,
  rankLimit: 10,
  announceLevelUp: true,
  requireGroupWhitelist: true,
  allowDm: false,
  commandExclusive: true,
  groupWhitelistJids: [],
  debugMode: false,
  logLevel: 'info',
  rankCardImage: true,
  dashboardEnabled: true,
  dashboardHost: '127.0.0.1',
  dashboardPort: 8790,
  // jogos (economia: sinks na /loja; farm lento)
  flipMin: 5,
  flipMax: 80,
  flipCooldownMs: 45_000,
  jobMin: 5,
  jobMax: 14,
  jobCooldownMs: 2 * 60 * 60_000, // 2h — não quebra economia
  luckyMin: 5,
  luckyMax: 40,
  luckyCooldownMs: 3 * 60 * 60_000, // 3h
  betMin: 5,
  betMax: 150,
  divorceCost: 40,
  titleMaxLen: 16,
});
