export const FUN_SCHEMA_VERSION = '7';

export const FUN_COMMANDS = Object.freeze({
  XP: 'xp',
  PERFIL: 'perfil',
  RANK: 'rank',
  RANK_COINS: 'rankcoins',
  RANK_MESSAGES: 'rankmessages',
  DAILY: 'daily',
  HELP: 'help',
  PAY: 'pay',
  COINS: 'coins',
  MARRY: 'marry',
  DIVORCE: 'divorce',
  SHIP: 'ship',
  ACCEPT: 'accept',
  DECLINE: 'decline',
  FLIP: 'flip',
  JOB: 'job',
  LUCKY: 'lucky',
  BET: 'bet',
  SHOP: 'shop',
  BUY: 'buy',
  TITLE: 'title',
  FACTION: 'faction',
  PANELINHA: 'panelinha',
  PANELINHA_GUIDE: 'panelinha_guide',
  PONTE: 'ponte',
  MISSION: 'mission',
  SQUAD: 'squad',
  EVENT: 'event',
  // Cassino
  ROULETTE: 'roulette',
  SLOT: 'slot',
  JACKPOT: 'jackpot',
  DICE_DUEL: 'dice_duel',
  CRASH: 'crash',
  CASHOUT: 'cashout',
  BLACKJACK: 'blackjack',
  HIT: 'hit',
  STAND: 'stand',
  TOURNAMENT: 'tournament',
  RANK_CASINO: 'rankcasino',
  // DM / escopo
  GROUP_SCOPE: 'group_scope',
  // Mídia
  STICKER: 'sticker',
});

/**
 * Com `replyCommandsInPrivate=true`, estes comandos continuam no grupo
 * (duelo/aposta, facções e interações sociais que precisam de visibilidade).
 */
export const FUN_PUBLIC_GROUP_COMMANDS = Object.freeze(
  new Set([
    FUN_COMMANDS.BET,
    FUN_COMMANDS.ACCEPT,
    FUN_COMMANDS.DECLINE,
    FUN_COMMANDS.FACTION,
    FUN_COMMANDS.PANELINHA,
    FUN_COMMANDS.PONTE,
    FUN_COMMANDS.MISSION,
    FUN_COMMANDS.SQUAD,
    FUN_COMMANDS.EVENT,
    // social: o outro jogador precisa ver no grupo
    FUN_COMMANDS.MARRY,
    FUN_COMMANDS.DIVORCE,
    FUN_COMMANDS.SHIP,
    FUN_COMMANDS.PAY,
    // cassino social / mesa
    FUN_COMMANDS.DICE_DUEL,
    FUN_COMMANDS.TOURNAMENT,
    FUN_COMMANDS.JACKPOT,
  ])
);

export const FUN_COMMAND_ALIASES = Object.freeze({
  xp: FUN_COMMANDS.XP,
  perfil: FUN_COMMANDS.PERFIL,
  profile: FUN_COMMANDS.PERFIL,
  rank: FUN_COMMANDS.RANK,
  top: FUN_COMMANDS.RANK,
  leaderboard: FUN_COMMANDS.RANK,
  rankcoins: FUN_COMMANDS.RANK_COINS,
  topcoins: FUN_COMMANDS.RANK_COINS,
  coinrank: FUN_COMMANDS.RANK_COINS,
  moedasrank: FUN_COMMANDS.RANK_COINS,
  rankmoedas: FUN_COMMANDS.RANK_COINS,
  rankmessages: FUN_COMMANDS.RANK_MESSAGES,
  rankmsg: FUN_COMMANDS.RANK_MESSAGES,
  topmsg: FUN_COMMANDS.RANK_MESSAGES,
  topmensagens: FUN_COMMANDS.RANK_MESSAGES,
  mensagens: FUN_COMMANDS.RANK_MESSAGES,
  topchat: FUN_COMMANDS.RANK_MESSAGES,
  maisativos: FUN_COMMANDS.RANK_MESSAGES,
  daily: FUN_COMMANDS.DAILY,
  diario: FUN_COMMANDS.DAILY,
  help: FUN_COMMANDS.HELP,
  ajuda: FUN_COMMANDS.HELP,
  pay: FUN_COMMANDS.PAY,
  pagar: FUN_COMMANDS.PAY,
  coins: FUN_COMMANDS.COINS,
  moedas: FUN_COMMANDS.COINS,
  saldo: FUN_COMMANDS.COINS,
  marry: FUN_COMMANDS.MARRY,
  casar: FUN_COMMANDS.MARRY,
  divorce: FUN_COMMANDS.DIVORCE,
  divorciar: FUN_COMMANDS.DIVORCE,
  ship: FUN_COMMANDS.SHIP,
  aceitar: FUN_COMMANDS.ACCEPT,
  accept: FUN_COMMANDS.ACCEPT,
  sim: FUN_COMMANDS.ACCEPT,
  yes: FUN_COMMANDS.ACCEPT,
  recusar: FUN_COMMANDS.DECLINE,
  recusa: FUN_COMMANDS.DECLINE,
  decline: FUN_COMMANDS.DECLINE,
  nao: FUN_COMMANDS.DECLINE,
  não: FUN_COMMANDS.DECLINE,
  no: FUN_COMMANDS.DECLINE,
  cf: FUN_COMMANDS.FLIP,
  flip: FUN_COMMANDS.FLIP,
  caracoroa: FUN_COMMANDS.FLIP,
  coinflip: FUN_COMMANDS.FLIP,
  job: FUN_COMMANDS.JOB,
  trabalhar: FUN_COMMANDS.JOB,
  work: FUN_COMMANDS.JOB,
  sorte: FUN_COMMANDS.LUCKY,
  lucky: FUN_COMMANDS.LUCKY,
  roleta: FUN_COMMANDS.ROULETTE,
  roulette: FUN_COMMANDS.ROULETTE,
  roletae: FUN_COMMANDS.ROULETTE,
  slot: FUN_COMMANDS.SLOT,
  slots: FUN_COMMANDS.SLOT,
  caça: FUN_COMMANDS.SLOT,
  caca: FUN_COMMANDS.SLOT,
  jackpot: FUN_COMMANDS.JACKPOT,
  pot: FUN_COMMANDS.JACKPOT,
  desafio: FUN_COMMANDS.DICE_DUEL,
  dados: FUN_COMMANDS.DICE_DUEL,
  d20: FUN_COMMANDS.DICE_DUEL,
  dice: FUN_COMMANDS.DICE_DUEL,
  crash: FUN_COMMANDS.CRASH,
  foguete: FUN_COMMANDS.CRASH,
  sair: FUN_COMMANDS.CASHOUT,
  cashout: FUN_COMMANDS.CASHOUT,
  descer: FUN_COMMANDS.CASHOUT,
  bj: FUN_COMMANDS.BLACKJACK,
  blackjack: FUN_COMMANDS.BLACKJACK,
  21: FUN_COMMANDS.BLACKJACK,
  hit: FUN_COMMANDS.HIT,
  carta: FUN_COMMANDS.HIT,
  stand: FUN_COMMANDS.STAND,
  parar: FUN_COMMANDS.STAND,
  torneio: FUN_COMMANDS.TOURNAMENT,
  tournament: FUN_COMMANDS.TOURNAMENT,
  torneiocassino: FUN_COMMANDS.TOURNAMENT,
  rankcassino: FUN_COMMANDS.RANK_CASINO,
  rankcasino: FUN_COMMANDS.RANK_CASINO,
  topcassino: FUN_COMMANDS.RANK_CASINO,
  grupo: FUN_COMMANDS.GROUP_SCOPE,
  group: FUN_COMMANDS.GROUP_SCOPE,
  grupos: FUN_COMMANDS.GROUP_SCOPE,
  meugrupo: FUN_COMMANDS.GROUP_SCOPE,
  fig: FUN_COMMANDS.STICKER,
  figurinha: FUN_COMMANDS.STICKER,
  sticker: FUN_COMMANDS.STICKER,
  s: FUN_COMMANDS.STICKER,
  aposta: FUN_COMMANDS.BET,
  bet: FUN_COMMANDS.BET,
  apostar: FUN_COMMANDS.BET,
  loja: FUN_COMMANDS.SHOP,
  shop: FUN_COMMANDS.SHOP,
  store: FUN_COMMANDS.SHOP,
  comprar: FUN_COMMANDS.BUY,
  buy: FUN_COMMANDS.BUY,
  titulo: FUN_COMMANDS.TITLE,
  title: FUN_COMMANDS.TITLE,
  faccao: FUN_COMMANDS.FACTION,
  facção: FUN_COMMANDS.FACTION,
  faction: FUN_COMMANDS.FACTION,
  panelinha: FUN_COMMANDS.PANELINHA,
  // guia completo (DM) — nomes diferentes do relatório /panelinha
  panelinhas: FUN_COMMANDS.PANELINHA_GUIDE,
  comopanelinha: FUN_COMMANDS.PANELINHA_GUIDE,
  guiapanelinha: FUN_COMMANDS.PANELINHA_GUIDE,
  guiafaccao: FUN_COMMANDS.PANELINHA_GUIDE,
  comofaccao: FUN_COMMANDS.PANELINHA_GUIDE,
  ponte: FUN_COMMANDS.PONTE,
  missao: FUN_COMMANDS.MISSION,
  missão: FUN_COMMANDS.MISSION,
  mission: FUN_COMMANDS.MISSION,
  squad: FUN_COMMANDS.SQUAD,
  evento: FUN_COMMANDS.EVENT,
  event: FUN_COMMANDS.EVENT,
});

export const ACTION_TYPE = Object.freeze({
  MARRY: 'marry',
  BET_COINFLIP: 'bet_coinflip',
  BET_DICE: 'bet_dice',
});

export const DAY_MS = 24 * 60 * 60 * 1000;
export const PROPOSAL_TTL_MS = 5 * 60 * 1000;
export const BET_TTL_MS = 5 * 60 * 1000;
export const CRASH_TTL_MS = 45_000;
export const BLACKJACK_TTL_MS = 3 * 60_000;
export const TOURNAMENT_SIZE = 4;

/** Defaults do bot Fun standalone (não herda config do TMB). */
export const DEFAULT_FUN_CONFIG = Object.freeze({
  enabled: true,
  prefix: '/',
  cooldownMs: 60_000,
  xpMin: 15,
  xpMax: 25,
  dailyXp: 150,
  dailyCoins: 50,
  rankLimit: 10,
  announceLevelUp: true,
  requireGroupWhitelist: true,
  // DM: comandos no privado se for membro de grupo na whitelist
  allowDm: true,
  dmCommandsOnly: true,
  dmMembershipCacheTtlMs: 5 * 60_000,
  commandExclusive: true,
  groupWhitelistJids: [],
  debugMode: false,
  logLevel: 'info',
  rankCardImage: true,
  dashboardEnabled: true,
  dashboardHost: '127.0.0.1',
  dashboardPort: 8790,
  // jogos (economia: sinks na /loja; farm lento)
  flipMin: 5,
  flipMax: 80,
  flipCooldownMs: 45_000,
  jobMin: 5,
  jobMax: 14,
  jobCooldownMs: 2 * 60 * 60_000, // 2h — não quebra economia
  luckyMin: 5,
  luckyMax: 40,
  luckyCooldownMs: 3 * 60 * 60_000, // 3h
  betMin: 5,
  betMax: 150,
  divorceCost: 40,
  titleMaxLen: 16,
  // P0 — facções / ponte / missões / evento
  factionsEnabled: true,
  factionMaxMembers: 8,
  factionLeaveCost: 25,
  factionCreateCost: 50,
  bridgeMinActions: 10,
  bridgeDebuffThreshold: 0.25,
  bridgeDebuffXpMult: 0.9,
  missionSquadSize: 3,
  missionRewardPerMember: 30,
  missionDurationMs: 12 * 60 * 60_000,
  missionAutoSpawn: true,
  eventDurationMs: 90 * 60_000,
  eventCrossMultiplier: 2,
  eventCooldownMs: 6 * 60 * 60_000,
  // Eventos só o bot sorteia (surpresa)
  eventAutoSpawn: true,
  eventAutoSpawnChance: 0.028,
  eventHappyWeight: 0.5,
  eventCrossWeight: 0.5,
  // Ollama — flavor de mensagens (nunca decide resultado de jogo)
  ollamaEnabled: true,
  ollamaBaseUrl: 'http://127.0.0.1:11434',
  ollamaModel: 'gemma4:latest',
  ollamaTimeoutMs: 25_000,
  ollamaNumPredict: 80,
  ollamaTemperature: 0.85,
  ollamaMaxChars: 160,
  // -1 = modelo fica carregado até o Ollama reiniciar / outro unload
  ollamaKeepAlive: -1,
  ollamaWarmupOnBoot: true,
  ollamaWarmupTimeoutMs: 120_000,
  // reafirma residência a cada N ms (0 = só keep_alive do request; default 10 min)
  ollamaKeepAliveRefreshMs: 10 * 60_000,
  /**
   * Se true, respostas de comando vão no privado de quem pediu (menos spam no grupo).
   * Exceções: FUN_PUBLIC_GROUP_COMMANDS (aposta, facção, missões, marry, ship, pay…).
   * Default true — o grupo fica só com duelo/aposta/facção/social.
   */
  replyCommandsInPrivate: true,
  // Cassino
  casinoMin: 5,
  casinoMax: 100,
  casinoCooldownMs: 20_000,
  casinoHouseEdge: 0.03,
  jackpotRate: 0.01,
  jackpotMinHit: 50,
  rouletteCooldownMs: 15_000,
  slotCooldownMs: 20_000,
  crashMin: 5,
  crashMax: 80,
  crashCooldownMs: 30_000,
  crashMaxMult: 12,
  crashGrowthPerSec: 0.18,
  crashTtlMs: 45_000,
  blackjackMin: 5,
  blackjackMax: 80,
  blackjackCooldownMs: 25_000,
  diceDuelMin: 5,
  diceDuelMax: 150,
  tournamentEntryMin: 10,
  tournamentEntryMax: 80,
  tournamentSize: 4,
  happyHourDurationMs: 45 * 60_000,
  happyHourPayoutMult: 1.12,
  happyHourCooldownMs: 4 * 60 * 60_000,
});
