import { fireFragmentShader, fireVertexShader, particleFragmentShader, particleVertexShader } from './glFireShaders';
import { createFireTruck, createSphere, createUrbanBlock, type MeshData, type ScenePart } from './glFireGeometry';
import { add3, identity4, invert4, lerp3, lookAt, multiply4, normalize3, perspective, rayAABB, scale3, sub3, transformPoint, transpose4, type Mat4, type Vec3 } from './glFireMath';

export type CameraMode='tactical'|'firstPerson'|'truckRear'|'drone';
export type ParticleKind='water'|'mist'|'foam'|'spark'|'fire'|'smoke';
export interface RenderState { time:number; dt:number; thermal?:boolean; heat?:Record<string,number>; damage?:Record<string,number>; ladderElevation?:number; ladderRotation?:number; ladderExtension?:number; nozzleOrigin?:Vec3; nozzleDirection?:Vec3; spraying?:ParticleKind|null; }
export interface PickResult { part:ScenePart; distance:number; point:Vec3 }
interface GPU { vao:WebGLVertexArrayObject; count:number; type:number }
interface Particle { p:Vec3;v:Vec3;age:number;life:number;size:number;kind:number;color:[number,number,number,number];settled:boolean }
const materials:Record<string,{a:Vec3;e:Vec3;rough:number}>={asphalt:{a:[.045,.055,.065],e:[0,0,0],rough:.18},concrete:{a:[.45,.46,.44],e:[0,0,0],rough:.85},building:{a:[.34,.31,.28],e:[0,0,0],rough:.8},'brick-hot':{a:[.34,.12,.065],e:[.7,.08,.01],rough:.9},'window-fire':{a:[.12,.05,.01],e:[1,.25,.015],rough:.2},window:{a:[.07,.12,.17],e:[.03,.08,.13],rough:.12},'fire-red':{a:[.65,.015,.01],e:[0,0,0],rough:.28},'dark-steel':{a:[.04,.05,.06],e:[0,0,0],rough:.22},steel:{a:[.32,.35,.38],e:[0,0,0],rough:.22},aluminum:{a:[.55,.58,.6],e:[0,0,0],rough:.2},rubber:{a:[.012,.012,.014],e:[0,0,0],rough:.95},'emissive-red':{a:[.5,.01,.01],e:[1,0,.01],rough:.1},'emissive-blue':{a:[.01,.04,.5],e:[.01,.12,1],rough:.1},roof:{a:[.16,.07,.04],e:[0,0,0],rough:.9},bark:{a:[.13,.06,.025],e:[0,0,0],rough:1},foliage:{a:[.06,.19,.07],e:[0,0,0],rough:1}};

export class FirefighterOpenGLRenderer {
 readonly gl:WebGL2RenderingContext; private program:WebGLProgram; private particleProgram:WebGLProgram; private gpu=new Map<MeshData,GPU>(); private scene:ScenePart[]; private particles:Particle[]=[]; private particleVAO:WebGLVertexArrayObject; private particleBuffer:WebGLBuffer; private view=identity4();private projection=identity4();private cameraPos:Vec3=[24,22,24];private target:Vec3=[0,3,0];private yaw=.8;private pitch=.65;private distance=34;private cameraMode:CameraMode='tactical';private pointerDown=false;private lastPointer=[0,0];private selected:ScenePart|null=null; private width=1;private height=1;
 constructor(readonly canvas:HTMLCanvasElement, seed=7){const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL2 não disponível');this.gl=gl;this.program=this.link(fireVertexShader,fireFragmentShader);this.particleProgram=this.link(particleVertexShader,particleFragmentShader);this.scene=[...createUrbanBlock(seed),...createFireTruck([0,0,14])];for(const x of this.scene)this.upload(x.mesh);this.particleVAO=gl.createVertexArray()!;this.particleBuffer=gl.createBuffer()!;this.setupParticleBuffer();gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.clearColor(.12,.18,.26,1);this.bindInput();this.resize()}
 private shader(type:number,src:string){const s=this.gl.createShader(type)!;this.gl.shaderSource(s,src);this.gl.compileShader(s);if(!this.gl.getShaderParameter(s,this.gl.COMPILE_STATUS))throw new Error(this.gl.getShaderInfoLog(s)||'Shader inválido');return s}
 private link(v:string,f:string){const p=this.gl.createProgram()!;this.gl.attachShader(p,this.shader(this.gl.VERTEX_SHADER,v));this.gl.attachShader(p,this.shader(this.gl.FRAGMENT_SHADER,f));this.gl.linkProgram(p);if(!this.gl.getProgramParameter(p,this.gl.LINK_STATUS))throw new Error(this.gl.getProgramInfoLog(p)||'Link GLSL falhou');return p}
 private upload(m:MeshData){if(this.gpu.has(m))return;const g=this.gl,vao=g.createVertexArray()!;g.bindVertexArray(vao);const attr=(loc:number,data:number[],size:number)=>{const b=g.createBuffer()!;g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);g.enableVertexAttribArray(loc);g.vertexAttribPointer(loc,size,g.FLOAT,false,0,0)};attr(0,m.positions,3);attr(1,m.normals,3);attr(2,m.uvs,2);attr(3,m.colors,4);const ib=g.createBuffer()!;g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,ib);const large=m.positions.length/3>65535;g.bufferData(g.ELEMENT_ARRAY_BUFFER,large?new Uint32Array(m.indices):new Uint16Array(m.indices),g.STATIC_DRAW);this.gpu.set(m,{vao,count:m.indices.length,type:large?g.UNSIGNED_INT:g.UNSIGNED_SHORT});g.bindVertexArray(null)}
 private setupParticleBuffer(){const g=this.gl;g.bindVertexArray(this.particleVAO);g.bindBuffer(g.ARRAY_BUFFER,this.particleBuffer);const stride=13*4;[3,3,4,1,1].forEach((size,i)=>{const offsets=[0,3,6,10,11];g.enableVertexAttribArray(i);g.vertexAttribPointer(i,size,g.FLOAT,false,stride,offsets[i]*4)});g.enableVertexAttribArray(5);g.vertexAttribPointer(5,1,g.FLOAT,false,stride,12*4);g.bindVertexArray(null)}
 resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.floor(this.canvas.clientWidth*d),h=Math.floor(this.canvas.clientHeight*d);if(w!==this.canvas.width||h!==this.canvas.height){this.canvas.width=w;this.canvas.height=h}this.width=w;this.height=h;this.gl.viewport(0,0,w,h);this.projection=perspective(Math.PI/3,w/Math.max(h,1),.08,180)}
 setCameraMode(mode:CameraMode){this.cameraMode=mode}
 orbit(dx:number,dy:number){this.yaw+=dx*.006;this.pitch=Math.max(.12,Math.min(1.48,this.pitch+dy*.006))} zoom(delta:number){this.distance=Math.max(6,Math.min(80,this.distance*Math.exp(delta*.001)))}
 private camera(dt:number){let eye:Vec3,target:Vec3,up:Vec3=[0,1,0];if(this.cameraMode==='tactical'){eye=[this.target[0]+Math.cos(this.yaw)*Math.cos(this.pitch)*this.distance,this.target[1]+Math.sin(this.pitch)*this.distance,this.target[2]+Math.sin(this.yaw)*Math.cos(this.pitch)*this.distance];target=this.target}else if(this.cameraMode==='firstPerson'){eye=[-3,1.72,11];target=[-3+Math.cos(this.yaw)*Math.cos(this.pitch),1.72+Math.sin(this.pitch),11+Math.sin(this.yaw)*Math.cos(this.pitch)]}else if(this.cameraMode==='truckRear'){eye=[5,3,14];target=[12,2,14]}else{eye=[0,55,0];target=[0,0,0];up=[0,0,-1]}this.cameraPos=lerp3(this.cameraPos,eye,1-Math.exp(-dt*8));this.view=lookAt(this.cameraPos,target,up)}
 render(state:RenderState){this.resize();this.camera(state.dt);this.updateParticles(state);const g=this.gl;g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.program);this.mat4('uView',this.view);this.mat4('uProjection',this.projection);this.v3('uCameraPos',this.cameraPos);this.v3('uSunDirection',[.25,-1,.3]);this.v3('uSunColor',[.7,.78,.92]);this.v3('uAmbientColor',[.14,.17,.22]);this.v3('uFogColor',[.16,.2,.27]);this.f('uFogDensity',.003);this.f('uSmokeDensity',.65);this.f('uTime',state.time);this.lights(state.time);for(const part of this.scene)this.drawPart(part,state);this.drawParticles(state.time);}
 private drawPart(part:ScenePart,state:RenderState){const g=this.gl,gpu=this.gpu.get(part.mesh)!;const model=part.transform;const damage=state.damage?.[part.name]||0,heat=state.heat?.[part.name]||(part.material==='window-fire' ? .8 : 0);const mat=materials[part.material]||materials.building;this.mat4('uModel',model);const inv=invert4(model),normal=inv?transpose4(inv):identity4();g.uniformMatrix3fv(g.getUniformLocation(this.program,'uNormalMatrix'),false,new Float32Array([normal[0],normal[1],normal[2],normal[4],normal[5],normal[6],normal[8],normal[9],normal[10]]));let albedo=scale3(mat.a,1-damage*.72);if(state.thermal)albedo=this.thermalColor(heat);this.v3('uAlbedo',albedo);this.v3('uEmissive',state.thermal?this.thermalColor(heat):mat.e);this.f('uHeat',state.thermal?heat*2:heat);this.f('uRoughness',part.material==='asphalt'?.12:mat.rough);g.uniform1i(g.getUniformLocation(this.program,'uFaceNormals'),0);g.bindVertexArray(gpu.vao);g.drawElements(g.TRIANGLES,gpu.count,gpu.type,0)}
 private thermalColor(t:number):Vec3{t=Math.max(0,Math.min(1,t));return t<.25?[0,t*2,1]:t<.5?[0,(t-.25)*4,1-(t-.25)*4]:t<.75?[(t-.5)*4,1,0]:[1,1,(t-.75)*4]}
 private lights(time:number){const g=this.gl,lights=[{p:[-1.8,3,13.35] as Vec3,c:[1,.01,.01] as Vec3},{p:[-1.8,3,14.65] as Vec3,c:[.01,.08,1] as Vec3},{p:[-10,7,-10] as Vec3,c:[1,.18,.015] as Vec3},{p:[10,10,10] as Vec3,c:[1,.12,.01] as Vec3}];g.uniform1i(g.getUniformLocation(this.program,'uLightCount'),lights.length);lights.forEach((l,i)=>{const a=time*7+(i<2?i*Math.PI:0),p:Vec3 = i < 2 ? [l.p[0]+Math.cos(a)*.25,l.p[1],l.p[2]+Math.sin(a)*.25] : l.p;this.v3(`uLights[${i}].position`,p);this.v3(`uLights[${i}].color`,l.c);this.f(`uLights[${i}].intensity`,i<2?8:11);this.f(`uLights[${i}].radius`,i<2?13:18);this.f(`uLights[${i}].flicker`,i<2?0:1)})}
 emit(kind:ParticleKind,origin:Vec3,dir:Vec3,count=12){const ids={water:0,mist:0,foam:1,spark:2,fire:3,smoke:4},id=ids[kind];for(let i=0;i<count&&this.particles.length<5000;i++){const spread=kind==='water'?.035:kind==='mist'?.18:.35,d=normalize3([dir[0]+(Math.random()-.5)*spread,dir[1]+(Math.random()-.5)*spread,dir[2]+(Math.random()-.5)*spread]);const speed=kind==='water'?24:kind==='mist'?10:kind==='foam'?13:kind==='spark'?6:1.5;this.particles.push({p:[...origin],v:scale3(d,speed*(.8+Math.random()*.4)),age:0,life:kind==='smoke'?6:kind==='fire'?1.5:2.5,size:kind==='smoke'?120:kind==='mist'?35:24,kind:id,color:[1,1,1,1],settled:false})}}
 private updateParticles(s:RenderState){if(s.spraying&&s.nozzleOrigin&&s.nozzleDirection)this.emit(s.spraying,s.nozzleOrigin,s.nozzleDirection,s.spraying==='mist'?24:10);for(const p of this.particles){p.age+=s.dt;if(p.settled)continue;const buoy=p.kind>=3?2.2:0;p.v[1]+=(-9.81*(p.kind<=1?1:.08)+buoy)*s.dt;p.v[0]+=.25*s.dt;p.p=add3(p.p,scale3(p.v,s.dt));if(p.p[1]<.1){if(p.kind===1){p.p[1]=.1;p.v=[0,0,0];p.settled=true;p.life+=5}else{p.p[1]=.1;p.v[1]*=-.22}}for(const part of this.scene){if(!part.tags?.includes('flammable')||p.kind>1)continue;const inv=invert4(part.transform);if(!inv)continue;const local=transformPoint(inv,p.p);if(rayAABB(local,normalize3(p.v),part.mesh.bounds)?.distance===0){p.v=scale3(p.v,-.1);p.age=p.life}}}this.particles=this.particles.filter(p=>p.age<p.life)}
 private drawParticles(time:number){if(!this.particles.length)return;const g=this.gl,data:number[]=[];for(const p of this.particles)data.push(...p.p,...p.v,...p.color,p.size,time-p.age,p.life);g.useProgram(this.particleProgram);this.mat4p('uView',this.view);this.mat4p('uProjection',this.projection);this.v3p('uEmitter',[0,0,0]);this.v3p('uAcceleration',[0,0,0]);this.v3p('uWind',[.2,0,.1]);this.fp('uTime',time);g.bindVertexArray(this.particleVAO);g.bindBuffer(g.ARRAY_BUFFER,this.particleBuffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.DYNAMIC_DRAW);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);for(let type=0;type<5;type++){g.uniform1i(g.getUniformLocation(this.particleProgram,'uParticleType'),type);g.drawArrays(g.POINTS,0,this.particles.length)}g.depthMask(true);g.disable(g.BLEND)}
 pick(clientX:number,clientY:number):PickResult|null{const rect=this.canvas.getBoundingClientRect(),x=(clientX-rect.left)/rect.width*2-1,y=1-(clientY-rect.top)/rect.height*2,inv=invert4(multiply4(this.projection,this.view));if(!inv)return null;const near=transformPoint(inv,[x,y,-1]),far=transformPoint(inv,[x,y,1]),dir=normalize3(sub3(far,near));let best:PickResult|null=null;for(const part of this.scene){const mi=invert4(part.transform);if(!mi)continue;const o=transformPoint(mi,near),d=normalize3(sub3(transformPoint(mi,add3(near,dir)),o)),hit=rayAABB(o,d,part.mesh.bounds);if(hit){const point=transformPoint(part.transform,hit.point),distance=Math.hypot(...sub3(point,near));if(!best||distance<best.distance)best={part,distance,point}}}this.selected=best?.part||null;return best}
 aimAt(x:number,y:number,origin:Vec3):Vec3|null{const hit=this.pick(x,y);return hit?normalize3(sub3(hit.point,origin)):null}
 private bindInput(){this.canvas.addEventListener('pointerdown',e=>{this.pointerDown=true;this.lastPointer=[e.clientX,e.clientY];this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(this.pointerDown&&this.cameraMode==='tactical'){this.orbit(e.clientX-this.lastPointer[0],e.clientY-this.lastPointer[1]);this.lastPointer=[e.clientX,e.clientY]}});this.canvas.addEventListener('pointerup',e=>{this.pointerDown=false;this.pick(e.clientX,e.clientY)});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY)},{passive:false})}
 dispose(){const g=this.gl;for(const x of this.gpu.values())g.deleteVertexArray(x.vao);g.deleteVertexArray(this.particleVAO);g.deleteBuffer(this.particleBuffer);g.deleteProgram(this.program);g.deleteProgram(this.particleProgram)}
 private mat4(n:string,m:Mat4){this.gl.uniformMatrix4fv(this.gl.getUniformLocation(this.program,n),false,m)}private v3(n:string,v:Vec3){this.gl.uniform3fv(this.gl.getUniformLocation(this.program,n),v)}private f(n:string,v:number){this.gl.uniform1f(this.gl.getUniformLocation(this.program,n),v)}private mat4p(n:string,m:Mat4){this.gl.uniformMatrix4fv(this.gl.getUniformLocation(this.particleProgram,n),false,m)}private v3p(n:string,v:Vec3){this.gl.uniform3fv(this.gl.getUniformLocation(this.particleProgram,n),v)}private fp(n:string,v:number){this.gl.uniform1f(this.gl.getUniformLocation(this.particleProgram,n),v)}
}
