import type { Mat4, Vec3, AABB } from './glFireMath';
import { emptyAABB, expandAABB, identity4, multiply4, rotationZ4, scaling4, transformPoint, translation4 } from './glFireMath';
export interface MeshData { positions:number[]; normals:number[]; uvs:number[]; colors:number[]; indices:number[]; bounds:AABB }
export interface ScenePart { name:string; mesh:MeshData; transform:Mat4; material:string; tags?:string[] }
const mesh=():MeshData=>({positions:[],normals:[],uvs:[],colors:[],indices:[],bounds:emptyAABB()});
function vertex(m:MeshData,p:Vec3,n:Vec3,uv:[number,number],c=[1,1,1,1]){m.positions.push(...p);m.normals.push(...n);m.uvs.push(...uv);m.colors.push(...c);m.bounds=expandAABB(m.bounds,p);return m.positions.length/3-1}
function quad(m:MeshData,a:Vec3,b:Vec3,c:Vec3,d:Vec3,n:Vec3,col?:number[]){const i=vertex(m,a,n,[0,0],col),j=vertex(m,b,n,[1,0],col),k=vertex(m,c,n,[1,1],col),l=vertex(m,d,n,[0,1],col);m.indices.push(i,j,k,i,k,l)}
export function createBox(w=1,h=1,d=1,bevel=0):MeshData {if(bevel>0)return createBeveledBox(w,h,d,bevel);const m=mesh(),x=w/2,y=h/2,z=d/2;quad(m,[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z],[0,0,1]);quad(m,[x,-y,-z],[-x,-y,-z],[-x,y,-z],[x,y,-z],[0,0,-1]);quad(m,[x,-y,z],[x,-y,-z],[x,y,-z],[x,y,z],[1,0,0]);quad(m,[-x,-y,-z],[-x,-y,z],[-x,y,z],[-x,y,-z],[-1,0,0]);quad(m,[-x,y,z],[x,y,z],[x,y,-z],[-x,y,-z],[0,1,0]);quad(m,[-x,-y,-z],[x,-y,-z],[x,-y,z],[-x,-y,z],[0,-1,0]);return m}
export function createBeveledBox(w=1,h=1,d=1,b=.08):MeshData {const m=mesh(),x=w/2,y=h/2,z=d/2;b=Math.min(b,x,y,z);const faces:[number,Vec3,Vec3][]=[[0,[1,0,0],[x,0,0]],[0,[-1,0,0],[-x,0,0]],[1,[0,1,0],[0,y,0]],[1,[0,-1,0],[0,-y,0]],[2,[0,0,1],[0,0,z]],[2,[0,0,-1],[0,0,-z]]];for(const [axis,n,o] of faces){const u=(axis===0?[0,y-b,0]:[x-b,0,0]) as Vec3,v=(axis===2?[0,y-b,0]:[0,0,z-b]) as Vec3;quad(m,[o[0]-u[0]-v[0],o[1]-u[1]-v[1],o[2]-u[2]-v[2]],[o[0]+u[0]-v[0],o[1]+u[1]-v[1],o[2]+u[2]-v[2]],[o[0]+u[0]+v[0],o[1]+u[1]+v[1],o[2]+u[2]+v[2]],[o[0]-u[0]+v[0],o[1]-u[1]+v[1],o[2]-u[2]+v[2]],n)}// compact rounded approximation: bevel edges via cylinders
return m}
export function createCylinder(radius=.5,height=1,segments=24,cap=true):MeshData {const m=mesh(),y=height/2;for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,b=(i+1)/segments*Math.PI*2,n1:[number,number,number]=[Math.cos(a),0,Math.sin(a)],n2:[number,number,number]=[Math.cos(b),0,Math.sin(b)];const k=m.positions.length/3;vertex(m,[radius*n1[0],-y,radius*n1[2]],n1,[i/segments,0]);vertex(m,[radius*n2[0],-y,radius*n2[2]],n2,[(i+1)/segments,0]);vertex(m,[radius*n2[0],y,radius*n2[2]],n2,[(i+1)/segments,1]);vertex(m,[radius*n1[0],y,radius*n1[2]],n1,[i/segments,1]);m.indices.push(k,k+1,k+2,k,k+2,k+3);if(cap){const top=vertex(m,[0,y,0],[0,1,0],[.5,.5]),bot=vertex(m,[0,-y,0],[0,-1,0],[.5,.5]);const ta=vertex(m,[radius*n1[0],y,radius*n1[2]],[0,1,0],[.5+n1[0]/2,.5+n1[2]/2]),tb=vertex(m,[radius*n2[0],y,radius*n2[2]],[0,1,0],[.5+n2[0]/2,.5+n2[2]/2]);const ba=vertex(m,[radius*n1[0],-y,radius*n1[2]],[0,-1,0],[0,0]),bb=vertex(m,[radius*n2[0],-y,radius*n2[2]],[0,-1,0],[0,0]);m.indices.push(top,ta,tb,bot,bb,ba)}}return m}
export function createSphere(radius=.5,lat=16,lon=24,hemisphere=false):MeshData {const m=mesh(),max=hemisphere?Math.PI/2:Math.PI;for(let y=0;y<=lat;y++){const p=y/lat*max;for(let x=0;x<=lon;x++){const t=x/lon*Math.PI*2,n:Vec3=[Math.sin(p)*Math.cos(t),Math.cos(p),Math.sin(p)*Math.sin(t)];vertex(m,[n[0]*radius,n[1]*radius,n[2]*radius],n,[x/lon,y/lat])}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){const a=y*(lon+1)+x,b=a+lon+1;m.indices.push(a,b,a+1,b,b+1,a+1)}return m}
export function createCone(radius=.5,height=1,segments=24):MeshData {const m=mesh(),y=height/2;for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,b=(i+1)/segments*Math.PI*2,p1:Vec3=[radius*Math.cos(a),-y,radius*Math.sin(a)],p2:Vec3=[radius*Math.cos(b),-y,radius*Math.sin(b)],n1:Vec3=[Math.cos(a),radius/height,Math.sin(a)],n2:Vec3=[Math.cos(b),radius/height,Math.sin(b)];const k=m.positions.length/3;vertex(m,p1,n1,[0,0]);vertex(m,p2,n2,[1,0]);vertex(m,[0,y,0],[0,1,0],[.5,1]);m.indices.push(k,k+1,k+2);const c=vertex(m,[0,-y,0],[0,-1,0],[.5,.5]),i1=vertex(m,p1,[0,-1,0],[0,0]),i2=vertex(m,p2,[0,-1,0],[1,0]);m.indices.push(c,i2,i1)}return m}
export function createPyramid(w=1,h=1,d=1):MeshData {const m=mesh(),x=w/2,z=d/2,y=h/2,top:Vec3=[0,y,0],base=-y;const ps:Vec3[]=[[-x,base,-z],[x,base,-z],[x,base,z],[-x,base,z]];for(let i=0;i<4;i++){const a=ps[i],b=ps[(i+1)%4],n=cross(b,a,top);quadTri(m,a,b,top,n)}quad(m,ps[3],ps[2],ps[1],ps[0],[0,-1,0]);return m}
const cross=(b:Vec3,a:Vec3,t:Vec3):Vec3=>{const u=[b[0]-a[0],b[1]-a[1],b[2]-a[2]] as Vec3,v=[t[0]-a[0],t[1]-a[1],t[2]-a[2]] as Vec3,l=Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]);return[(u[1]*v[2]-u[2]*v[1])/l,(u[2]*v[0]-u[0]*v[2])/l,(u[0]*v[1]-u[1]*v[0])/l]};
function quadTri(m:MeshData,a:Vec3,b:Vec3,c:Vec3,n:Vec3){const i=vertex(m,a,n,[0,0]),j=vertex(m,b,n,[1,0]),k=vertex(m,c,n,[.5,1]);m.indices.push(i,j,k)}
const T=(p:Vec3,s:Vec3=[1,1,1])=>multiply4(translation4(p),scaling4(s));
export function createUrbanBlock(seed=1):ScenePart[]{const p:ScenePart[]=[];let r=seed;const rand=()=>((r=Math.imul(r,1664525)+1013904223|0)>>>0)/4294967296;p.push({name:'asphalt',mesh:createBox(38,.18,38),transform:T([0,-.12,0]),material:'asphalt'},{name:'sidewalk',mesh:createBox(34,.22,34),transform:T([0,.02,0]),material:'concrete'});for(let z=-1;z<=1;z+=2)for(let x=-1;x<=1;x+=2){const floors=2+Math.floor(rand()*5),w=9+rand()*4,d=8+rand()*4,h=floors*2.8;p.push({name:`building-${x}-${z}`,mesh:createBeveledBox(w,h,d,.12),transform:T([x*10,h/2+.2,z*10]),material:rand()<.4?'brick-hot':'building',tags:['flammable']});for(let f=0;f<floors;f++)for(let k=-1;k<=1;k++)p.push({name:'window',mesh:createBox(1.15,1.2,.08),transform:T([x*10+k*2.2,1.5+f*2.7,z*10-z*(d/2+.05)]),material:rand()<.28?'window-fire':'window'});if(floors<4)p.push({name:'roof',mesh:createPyramid(w+1,2,d+1),transform:T([x*10,h+1,z*10]),material:'roof'})}for(let i=-1;i<=1;i++)p.push({name:'tree-trunk',mesh:createCylinder(.28,2.4,12),transform:T([i*7,1.2,-16]),material:'bark'},{name:'tree-crown',mesh:createSphere(1.5,10,14),transform:T([i*7,3.2,-16]),material:'foliage'});p.push(...createHydrant([-14,.7,13]));return p}
export function createHydrant(pos:Vec3):ScenePart[]{return[{name:'hydrant-body',mesh:createCylinder(.42,1.2,18),transform:T(pos),material:'fire-red'},{name:'hydrant-dome',mesh:createSphere(.46,8,16,true),transform:T([pos[0],pos[1]+.6,pos[2]]),material:'fire-red'},{name:'hydrant-cap',mesh:createCylinder(.2,.7,12),transform:multiply4(T([pos[0]+.45,pos[1],pos[2]]),rotationZ4(Math.PI/2)),material:'steel'}]}
export function createFireTruck(pos:Vec3=[0,0,0]):ScenePart[]{const p:ScenePart[]=[];p.push({name:'truck-chassis',mesh:createBeveledBox(6,.7,2.4,.12),transform:T([pos[0],pos[1]+.75,pos[2]]),material:'dark-steel'},{name:'truck-cab',mesh:createBeveledBox(2.1,2.1,2.3,.18),transform:T([pos[0]-1.8,pos[1]+1.75,pos[2]]),material:'fire-red'},{name:'water-tank',mesh:createCylinder(.85,3.1,24),transform:multiply4(T([pos[0]+1,pos[1]+1.65,pos[2]]),rotationZ4(Math.PI/2)),material:'fire-red'});for(const x of [-2,1.8])for(const z of [-1.15,1.15])p.push({name:'wheel',mesh:createCylinder(.52,.32,20),transform:multiply4(T([pos[0]+x,pos[1]+.55,pos[2]+z]),rotationZ4(Math.PI/2)),material:'rubber'});for(const z of [-.65,.65])p.push({name:z<0?'siren-blue':'siren-red',mesh:createSphere(.2,8,12,true),transform:T([pos[0]-1.8,pos[1]+2.9,pos[2]+z]),material:z<0?'emissive-blue':'emissive-red',tags:['siren']});p.push(...createMagirusLadder([pos[0]+.8,pos[1]+2.45,pos[2]],-.18,1));return p}
export function createMagirusLadder(pivot:Vec3,angle=-.2,extension=1):ScenePart[]{const parts:ScenePart[]=[];for(let s=0;s<3;s++){const length=3.6,offset=s*2.7*extension,base=multiply4(translation4(pivot),multiply4(rotationZ4(angle),translation4([offset,0,0])));parts.push({name:`ladder-rail-${s}-a`,mesh:createBox(length,.12,.12),transform:multiply4(base,translation4([length/2,0,-.55])),material:'aluminum',tags:['articulated']},{name:`ladder-rail-${s}-b`,mesh:createBox(length,.12,.12),transform:multiply4(base,translation4([length/2,0,.55])),material:'aluminum',tags:['articulated']});for(let i=0;i<7;i++)parts.push({name:'ladder-rung',mesh:createCylinder(.055,1.1,8),transform:multiply4(base,multiply4(translation4([i*.5,.0,0]),rotationZ4(Math.PI/2))),material:'aluminum'})}return parts}
export function transformMesh(source:MeshData,matrix:Mat4):MeshData{const out={...source,positions:[],normals:[...source.normals],uvs:[...source.uvs],colors:[...source.colors],indices:[...source.indices],bounds:emptyAABB()} as MeshData;for(let i=0;i<source.positions.length;i+=3){const p=transformPoint(matrix,[source.positions[i],source.positions[i+1],source.positions[i+2]]);out.positions.push(...p);out.bounds=expandAABB(out.bounds,p)}return out}
